[package]
name = "burnboard"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "server"
path = "src/bin/server.rs"
required-features = ["command-line"]

[features]

default = []
command-line = ["tokio", "axum", "tower", "tower-http", "clap"]

[dependencies]
# Protobuf
prost = "0.14"
prost-types = "0.14"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# IO and encoding
bytes = "1.5"
byteorder = "1.5"
crc32c = "0.6"

# System Info
sys-info = "0.9"

# Error handling
thiserror = "2.0"
anyhow = "1.0"

# Async runtime
tokio = { version = "1.35", features = ["full"], optional = true  }

# Web server
axum = { version = "0.8", optional = true }
tower = { version = "0.5", optional = true }
tower-http = { version = "0.6", features = ["fs", "trace"], optional = true  }
clap = { version = "4.3", features = ["derive"], optional = true }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }



[build-dependencies]
prost-build = "0.14"
